export {default as Banner } from "./Banner"
export {default as MasterCoding } from "./MasterCoding"
export {default as CoursesSection } from "./CoursesSection"
export {default as Review } from "./Review"
export {default as News } from "./News"